const module = "EDITOR_ELEMENTS";

// C(-R)UD
export const CREATE_ELEMENT = `${module}/CREATE_ELEMENT`;
export const DELETE_SELECTED_ELEMENTS = `${module}/DELETE_SELECTED_ELEMENTS`;

export const APPEND_ELEMENT_POINT = `${module}/APPEND_ELEMENT_POINT`;
export const DELETE_ELEMENT_LAST_POINT = `${module}/DELETE_ELEMENT_LAST_POINT`;

export const CHANGE_ELEMENT_LAST_POINT = `${module}/CHANGE_ELEMENT_LAST_POINT`;
export const CHANGE_ELEMENT_ANGLE = `${module}/CHANGE_ELEMENT_ANGLE`;
export const CHANGE_ELEMENT_SIZE = `${module}/CHANGE_ELEMENT_SIZE`;
export const CHANGE_ELEMENT_POINT = `${module}/CHANGE_ELEMENT_POINT`;
export const CHANGE_ELEMENT_ATTRIBUTES = `${module}/CHANGE_ELEMENT_ATTRIBUTES`;

export const MOVE_ELEMENT_POINTS = `${module}/MOVE_ELEMENT_POINTS`;
export const MOVE_ELEMENTS_GROUP = `${module}/MOVE_ELEMENTS_GROUP`;

// LAYER OPERATIONS
export const MOVE_ELEMENTS_ON_TOP_LEVEL = `${module}/MOVE_ELEMENTS_ON_TOP_LEVEL`;
export const MOVE_ELEMENTS_ON_BOTTOM_LEVEL = `${module}/MOVE_ELEMENTS_ON_BOTTOM_LEVEL`;
export const MOVE_ELEMENTS_ON_FORWARD_LEVEL = `${module}/MOVE_ELEMENTS_ON_FORWARD_LEVEL`;
export const MOVE_ELEMENTS_ON_BACK_LEVEL = `${module}/MOVE_ELEMENTS_ON_BACK_LEVEL`;

// GROUP POSITION CHANGERS
export const ALIGN_ELEMENTS_LEFT = `${module}/ALIGN_ELEMENTS_LEFT`;
export const ALIGN_ELEMENTS_HORIZON = `${module}/ALIGN_ELEMENTS_HORIZON`;
export const ALIGN_ELEMENTS_RIGHT = `${module}/ALIGN_ELEMENTS_RIGHT`;
export const ALIGN_ELEMENTS_TOP = `${module}/ALIGN_ELEMENTS_TOP`;
export const ALIGN_ELEMENTS_VERTICAL = `${module}/ALIGN_ELEMENTS_VERTICAL`;
export const ALIGN_ELEMENTS_BOTTOM = `${module}/ALIGN_ELEMENTS_BOTTOM`;

// GROUP FUNCTION
export const GROUP_ELEMENTS = `${module}/GROUP_ELEMENTS`;
export const UNGROUP_ELEMENTS = `${module}/UNGROUP_ELEMENTS`;

// HISTORY
export const CREATE_HISTORY_CHANGE_POINT = `${module}/CREATE_HISTORY_CHANGE_POINT`;
