const module = "MIMIC_EDITOR";

export const SET_CANVAS_RECT_POSITION = `${module}/SET_CANVAS_RECT_POSITION`;
export const SET_CREATED_ELEMENT_ID = `${module}/SET_CREATED_ELEMENT_ID`;

export const SET_CREATION_MODE = `${module}/SET_CREATION_MODE`;
export const SET_EDIT_MODE = `${module}/SET_EDIT_MODE`;
export const SET_PREVIEW_MODE = `${module}/SET_PREVIEW_MODE`;

export const ADD_ELEMENT_TO_SELECTION = `${module}/ADD_ELEMENT_TO_SELECTION`;
export const SET_SELECTED_ELEMENTS = `${module}/SET_SELECTED_ELEMENTS`;
export const ABORT_SELECTION = `${module}/ABORT_SELECTION`;
export const DISABLE_SELECT_OPERATIONS = `${module}/DISABLE_SELECT_OPERATIONS`;
export const ENABLE_SELECT_OPERATIONS = `${module}/ENABLE_SELECT_OPERATIONS`;
export const UPDATE_AVAILABLE_OPERATIONS = `${module}/UPDATE_AVAILABLE_OPERATIONS`;

export const COPY_SELECTED_ELEMENTS_TO_BUFFER = `${module}/COPY_SELECTED_ELEMENTS_TO_BUFFER`;
export const PASTE_ELEMENTS_FROM_BUFFER = `${module}/PASTE_ELEMENTS_FROM_BUFFER`;

export const SET_SELECTION_AREA = `${module}/SET_SELECTION_AREA`;
export const SET_SELECTION_AREA_VISIBLE = `${module}/SET_SELECTION_AREA_VISIBLE`;
